aplay - Include missing time.h for time()
With salsa-lib,
  aplay.c: In function ‘compute_max_peak’:
  aplay.c:1207: warning: implicit declaration of function ‘time’